In [4]:
import pandas as pd
import numpy as np

In [5]:
product_data=pd.read_csv("../Data/Processed/products_cleaned.csv")
order_items_data=pd.read_csv("../Data/Processed/order_items_cleaned.csv")
category_translation_data=pd.read_csv("../Data/Raw/product_category_name_translation.csv")

In [6]:
# How many products are in the catalog? catalog means the collection of products available in the Products table.
Total_product_catalog=product_data["product_id"].nunique()
print(Total_product_catalog)

# The Olist product catalog contains 32,951 unique products.

32951

In [7]:
# How many unique product categories are there?
unique_products=product_data["product_category_name"].nunique()
print(unique_products)

# There is 73 unique product categories
# After removing products with missing category information, the dataset contains 73 unique product categories.

74

In [8]:
# Which categories have the most products?
category_total_products=product_data.groupby("product_category_name")[
    ["product_id"]
    ].count()

category_total_products.sort_values("product_id",ascending=False)

# The product category cama_mesa_banho has the most products 3029 among all the other categories while cds_dvds_musicais category has only 1 total 
# products

                               product_id
product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
...                                   ...
casa_conforto_2                         5
fashion_roupa_infanto_juvenil           5
pc_gamer                                3
seguros_e_servicos                      2
cds_dvds_musicais                       1

[74 rows x 1 columns]

In [9]:
# What are the key descriptive statistics of product attributes such as weight and photos?
descriptive_stats=product_data.describe()
descriptive_stats

# product_photos mean 2.188986 is higher then median 1.000000 so the distribution is rightly skewed as std is The standard deviation is relatively large compared with the mean(79.35%)indicating 
# substantial variability relative to the avg product photos and the value range from  1 to 20 giving a numerical range of 19 ,Q1 and median all equal
# to 1 indicating that at least 50% of the observation has product photos of 1 however the next 25% extends to 3 but the remaning last 25% extends 
# from 3 to 20 creating a long upper tail and indicating the unusal high presence of product photos value

# product weight mean 2276.472488 is higher then its median 700.000000 which tells that the distribution is right skewed and the std is also higher 
# 4282.038731 The standard deviation is much larger than the mean(188%) indicating substantial variability in product weight value and the value range from
# 0 to 40425 giving a numerical range of 40425 the quartile show that 75% of observations have product weight value at or below 1900.000000 and the 
# remaining 25% extends from 1900.00000 to 40425.000000 and the extreme range of upper 25% of quartile indicates a long upper tail and also suggests
# the presence of high product weight values which likely contribute to righ skewed distribution.

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [10]:
category_revenue=product_data.merge(
    order_items_data[["product_id","price","freight_value","order_id"]],
    on="product_id",
    how="left"
)
category_revenue

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,price,freight_value,order_id
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery,10.91,7.39,e17e4f88e31525f7deef66779844ddce
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art,248.00,17.99,5236307716393b7114b53ee991f36956
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure,79.80,7.82,01f66e58769f84129811d43eefd187fb
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby,112.30,9.54,143d00a4f2dde4e0364ee1821577adb3
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares,37.90,8.29,86cafb8794cb99a9b1b77fc8e48fbbbb
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories,29.90,16.11,59e88b7d3675e89aceaf86f372d3bc9a
112646,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories,29.90,23.28,6e4465d771f02e4fe335225de3c6c043
112647,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories,29.90,23.28,6e4465d771f02e4fe335225de3c6c043
112648,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories,29.90,23.28,6e4465d771f02e4fe335225de3c6c043
112649,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table,107.50,27.05,f3a47ba087f05d39a74ed1b653f0be1b

In [11]:
# Which product categories generate the highest revenue?

category_highest_revenue=category_revenue.groupby("product_category_name")[
    ["price"]
    ].sum()
category_highest_revenue.sort_values("price",ascending=False)

# beleza_saude product category generate the highest revenue 1258681.34 among all the other category while seguros_e_servicos generate lowest 
# revenue 283.29

                                    price
product_category_name
beleza_saude                   1258681.34
relogios_presentes             1205005.68
cama_mesa_banho                1036988.68
esporte_lazer                   988048.97
informatica_acessorios          911954.32
...                                   ...
flores                            1110.04
casa_conforto_2                    760.27
cds_dvds_musicais                  730.00
fashion_roupa_infanto_juvenil      569.85
seguros_e_servicos                 283.29

[74 rows x 1 columns]

In [12]:
# Which product categories have the highest number of items sold?

category_highest_items_sold=product_data.groupby("product_category_name")[
    ["product_id"]
    ].count()
category_highest_items_sold.sort_values("product_id",ascending=False)

# Highest number of items sold in cama_mesa_banho category that is 3029 while cds_dvds_musicais sold less items that is 1

                               product_id
product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
...                                   ...
casa_conforto_2                         5
fashion_roupa_infanto_juvenil           5
pc_gamer                                3
seguros_e_servicos                      2
cds_dvds_musicais                       1

[74 rows x 1 columns]

In [13]:
# Which products generate the highest revenue?

product_high_revenue=category_revenue.groupby("product_id")[
    ["price"]
    ].sum()
product_high_revenue.sort_values("price",ascending=False).head(1)

                                    price
product_id
bb50f2e236e5eea0100680137654686c  63885.0

In [14]:
# Which products have the highest sales volume?

product_high_sales_volume=category_revenue.groupby("product_id")[
    ["order_id"]
    ].count()
product_high_sales_volume.sort_values("order_id",ascending=False).head(1)

                                  order_id
product_id
aca2eb7d00ea1a7b8ebd4e68314663af       527

In [15]:
# Which categories have a high number of products but low sales volume?

category_analysis=(category_revenue.groupby("product_category_name")
                   .agg(
                       total_products=("product_id","count"),
                       sales_volume=("order_id","count")
                   )
                  )
high_product_low_Sales=category_analysis[
    (category_analysis["total_products"]>category_analysis["total_products"].mean()) &
    (category_analysis["sales_volume"]<category_analysis["sales_volume"].mean())
    ]

high_product_low_Sales.sort_values(
    "total_products",
    ascending=False
)

# suprisingly there is no product category which have high number of products but low sales volume

Empty DataFrame
Columns: [total_products, sales_volume]
Index: []

In [16]:
# Which categories generate high revenue relative to their number of products?

category_product=(category_revenue.groupby("product_category_name")
                  .agg(
                      revenue=("price","sum"),
                       number_of_products=("product_id","nunique")
                  
                 )
                 )
category_product["revenue_per_product"]=(
    category_product["revenue"]/category_product["number_of_products"]
)
category_product.sort_values("revenue_per_product",ascending=False)

# pcs product_category has high revenue per products while flores have lowest revenue per products

,revenue,number_of_products,revenue_per_product
product_category_name,,,
pcs,222963.13,30,7432.104333
portateis_casa_forno_e_cafe,47445.71,31,1530.506774
eletrodomesticos_2,113317.74,90,1259.086000
agro_industria_e_comercio,72530.47,74,980.141486
relogios_presentes,1205005.68,1329,906.701038
...,...,...,...
fashion_roupa_masculina,10797.82,95,113.661263
fashion_esporte,2119.51,19,111.553158
fashion_roupa_feminina,2803.64,27,103.838519
artes_e_artesanato,1814.01,19,95.474211
flores,1110.04,14,79.288571

In [17]:
# weight_affect_freight=(category_revenue.groupby("product_id")
#     .agg(
#         weight=("product_weight_g","sum"),
#         freight=("freight_value","sum")
#     ).corr()
#                       )
# weight_affect_freight
# The problem is product_weight_g is generally a product-level attribute. If the same product appears in 100 order items,its weight may appear 100 
# times. so instead of this we can take origibal product weight and freight value

In [18]:
# Does product weight affect freight value?
weight_affect_freight = category_revenue[
    ["product_weight_g", "freight_value"]
].corr()

weight_affect_freight

# # |     Correlation | Interpretation                 |
# | --------------: | ------------------------------ |
# | Close to **+1** | Strong positive relationship   |
# | Around **+0.5** | Moderate positive relationship |
# |    Around **0** | Little/no linear relationship  |
# | Around **-0.5** | Moderate negative relationship |
# | Close to **-1** | Strong negative relationship   |


# There is a positive correlation between weight and freight value of 0.757451 which indicates that the heavier the product weight is the higher the 
# shipping charge/freight values will be

                  product_weight_g  freight_value
product_weight_g           1.00000        0.61042
freight_value              0.61042        1.00000

In [19]:
# Do products with more photos generate higher sales?

product_photos_relation_sales=category_revenue[
    ["product_photos_qty","price"]
    ].corr()

product_photos_relation_sales

# product photos has almost no linear relation with sales as there are 0.051848 correlation between them which indicates that more photos do not 
# generate the high product sales

                    product_photos_qty     price
product_photos_qty            1.000000  0.051848
price                         0.051848  1.000000

In [20]:
# Which categories have the highest freight-to-price ratio?

category_freight_price=(category_revenue.groupby("product_category_name")
                        .agg(
                            freight=("freight_value","sum"),
                            price=("price","sum")
                        )
                       )
category_freight_price["freight_price_ratio"]=category_freight_price["freight"]/category_freight_price["price"]

category_freight_price.sort_values("freight_price_ratio",ascending=False)

# casa_conforto_2 has highest freight-to-price ratio while pcs has highest ratio

,freight,price,freight_price_ratio
product_category_name,,,
casa_conforto_2,410.31,760.27,0.539690
flores,488.87,1110.04,0.440408
moveis_colchao_e_estofado,1630.46,4368.08,0.373267
artigos_de_natal,3229.30,8800.82,0.366932
fraldas_higiene,573.68,1567.59,0.365963
...,...,...,...
agro_industria_e_comercio,5843.60,72530.47,0.080568
portateis_cozinha_e_preparadores_de_alimentos,309.76,3968.53,0.078054
telefonia_fixa,4637.81,59583.00,0.077838
portateis_casa_forno_e_cafe,2747.86,47445.71,0.057916
pcs,9836.30,222963.13,0.044116

In [21]:
# Which product characteristics are associated with higher revenue?

product_revenue_characteristics = (category_revenue[
    [
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm",
        "product_photos_qty",
        "product_name_lenght",
        "product_description_lenght",
        "price"
    ]
].corr()
                                  )

product_revenue_characteristics["price"].sort_values(ascending=False)

# product_weight has the strongest positive correlation with revenue among all the product characteristics while product height,description,width and
# length has weak correlation and product photos and produt name length has no linear relation with revenue

price                         1.000000
product_weight_g              0.338819
product_height_cm             0.223602
product_description_lenght    0.198166
product_width_cm              0.172467
product_length_cm             0.145811
product_photos_qty            0.051848
product_name_lenght           0.017001
Name: price, dtype: float64