In [3]:
import pandas as pd

In [4]:
seller_data=pd.read_csv("../Data/Processed/sellers_cleaned.csv")
order_items_data=pd.read_csv("../Data/Processed/order_items_cleaned.csv")
order_data=pd.read_csv("../Data/Processed/orders_cleaned.csv")
customer_data=pd.read_csv("../Data/Processed/customers_cleaned.csv")

In [5]:
# How many unique sellers are there?
unique_sellers=seller_data["seller_id"].nunique()
unique_sellers

# Total unique sellers are 3095 in olist seller data

3095

In [6]:
# How many sellers are there in each state?

seller_state=seller_data.groupby("seller_state")[
    ["seller_id"]
    ].nunique()

seller_state.sort_values("seller_id",ascending=False)

# Sao paulo state have highest number of unique sellers 1849 while PA have only 1 unique seller in total

              seller_id
seller_state
SP                 1849
PR                  349
MG                  244
SC                  190
RJ                  171
RS                  129
GO                   40
DF                   30
ES                   23
BA                   19
CE                   13
PE                    9
PB                    6
MS                    5
RN                    5
MT                    4
RO                    2
SE                    2
AM                    1
AC                    1
PI                    1
MA                    1
PA                    1

In [7]:
# Which states have the highest number of sellers?
highest_seller_state=seller_data.groupby("seller_state")[
    ["seller_id"]
    ].nunique()

highest_seller_state.sort_values("seller_id",ascending=False).head(1)

# Sao paulo state have highest numbers of sellers among all the other states

              seller_id
seller_state
SP                 1849

In [8]:
# What are the top 10 cities by seller count?
Top_10_seller_city=seller_data.groupby("seller_city")[
    ["seller_id"]
    ].nunique()

Top_10_seller_city.sort_values("seller_id",ascending=False).head(10)

# These are the top 10 city that have the highest seller count

                seller_id
seller_city
sao paulo             694
curitiba              127
rio de janeiro         96
belo horizonte         68
ribeirao preto         52
guarulhos              50
ibitinga               49
santo andre            45
campinas               41
maringa                40

In [9]:
seller_order_items=seller_data.merge(
    order_items_data[["seller_id","price","freight_value","order_id","product_id"]],
    on="seller_id",
    how="left"
)
seller_order_items

,seller_id,seller_zip_code_prefix,seller_city,seller_state,price,freight_value,order_id,product_id
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,106.20,9.56,4a90af3e85dd563884e2afeab1091394,ffb64e34a37740dafb6c88f1abd1fa61
1,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,101.70,15.92,6d953888a914b67350d5bc4d48f2acab,f4621f8ad6f54a2e3c408884068be46d
2,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,10.80,2.42,bc8a5de6abf5b14f98a6135a7fb46731,325a06bcce0da45b7f4ecf2797dd40e4
3,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,89.99,45.09,035201c3c82a97f8a25dd6bd5244b2d5,1c36a5285f7f3b1ed2637d7c528ce5ff
4,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,199.90,21.89,0504447548229e075dea8441b37b1e2a,8852eb03b04ec3268a66e9b696e25f6f
...,...,...,...,...,...,...,...,...
112645,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,16.05,7aa50aad959e4345b45b9732bc346a6e,e891d4a9622cae3b9fc2ec558bda155b
112646,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,10.96,aae373a2cc64ed2d1f262aa56e70b7e8,e891d4a9622cae3b9fc2ec558bda155b
112647,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,16.05,bc34d5b185152cb88b9f5db391dcd1cb,e891d4a9622cae3b9fc2ec558bda155b
112648,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,12.48,d1edb80f6670902ebbb11765b96873da,e891d4a9622cae3b9fc2ec558bda155b
112649,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,12.50,14.52,f7b6b85f6fd2cf9aac15731dca998844,179bb56045bec397c52ef3c8183dabb6

In [10]:
# Which sellers generate the highest revenue?
seller_revenue=seller_order_items.groupby("seller_id")[
    ["price","freight_value"]
    ].sum()
seller_revenue.sort_values("price",ascending=False).head(1)

                                      price  freight_value
seller_id
4869f7a5dfa277a7dca6462dcf3b52b2  229472.63       20168.07

In [11]:
# Which sellers sell the highest number of items?
seller_items=seller_order_items.groupby("seller_id")[
    ["product_id"]
    ].nunique()

seller_items.sort_values("product_id",ascending=False).head(1)

                                  product_id
seller_id
4a3ca9315b744ce9f8e9374361493884         399

In [12]:
# Which sellers receive the highest number of orders?
seller_items=seller_order_items.groupby("seller_id")[
    ["order_id"]
    ].count()

seller_items.sort_values("order_id",ascending=False).head(1)

                                  order_id
seller_id
6560211a19b47992c3666cc44a7e94c0      2033

In [13]:
# Which sellers have the highest average order value?

order_value=(order_items_data.groupby("seller_id")
             .agg(
                 total_order=("order_id","count"),
                 order_value=("price","sum")
             )
            )
order_value["avg_order_value"]=order_value["total_order"]/order_value["order_value"]
order_value.sort_values("avg_order_value",ascending=False).head(1)

                                  total_order  order_value  avg_order_value
seller_id
cf6f6bc4df3999b9c6440f124fb2f687            1          3.5         0.285714

In [14]:
# Which sellers contribute the most to total marketplace revenue?

total_marketplace_revenue=seller_order_items.groupby("seller_id")[
    ["price"]
    ].sum()

total_marketplace_revenue.sort_values("price",ascending=False).head(1)

                                      price
seller_id
4869f7a5dfa277a7dca6462dcf3b52b2  229472.63

In [15]:
# Which sellers have high sales volume but low revenue?

seller_sales_revenue=(seller_order_items.groupby("seller_id")
                      .agg(
                          sales_volume=("order_id","count"),
                          revenue=("price","sum")
                      )
                     )
high_sales_low_revenue=seller_sales_revenue[
    (seller_sales_revenue["sales_volume"]>seller_sales_revenue["sales_volume"].mean())&
    (seller_sales_revenue["revenue"]<seller_sales_revenue["revenue"].mean())
    ]

high_sales_low_revenue.head(1)

# sales_mean=seller_sales_revenue["sales_volume"].mean()
# revenue_mean=seller_sales_revenue["revenue"].mean()
# print(sales_mean)  #36.39741518578352
# print(revenue_mean)  # 4391.484232633279

                                  sales_volume  revenue
seller_id
002100f778ceb8431b7a1020ff7ab48f            55   1234.5

In [16]:
sales_revenue=seller_sales_revenue[
    ["sales_volume","revenue"]
    ].corr()
sales_revenue

# sales volume and revenue appear to be dependent on each other because the relationship between sales and revenue is positive relationship(0.795955)

              sales_volume   revenue
sales_volume      1.000000  0.795955
revenue           0.795955  1.000000

In [17]:
# Which seller states generate the highest revenue?
seller_state_revenue=seller_order_items.groupby("seller_state")[
    ["price"]
    ].sum()
seller_state_revenue.sort_values("price",ascending=False).head(1)

                   price
seller_state
SP            8753396.21

In [19]:
columns=[  
    "order_purchase_timestamp",            
     "order_approved_at",
     "order_delivered_carrier_date",  
     "order_delivered_customer_date",    
     "order_estimated_delivery_date"
]
for col in columns:
    order_data[col]=pd.to_datetime(
        order_data[col],format="mixed"
    )
    
order_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   order_purchase_year            99441 non-null  int64
 9   order_purchase_month           99441 non-null  int64
 10  order_purchase_month_name      99441 non-null  str
 11  order_delivery_time            96476 non-null  float64
 12  delivery_delay_days            96476 non-null  float64
 13  delivery_status                99441 non-null  str
dtypes: datetime64[us](5), float64(2), int64(2), str(5)
memory usage: 10.6 MB

In [21]:
seller_items=seller_order_items.merge(
    order_items_data[["order_id","seller_id"]],
    on="seller_id",
    how="left"
)
seller_items_order=seller_order_items.merge(
    order_data[["order_id","delivery_delay_days","order_delivery_time"]],
    on="order_id",
    how="left"
)
seller_items_order

,seller_id,seller_zip_code_prefix,seller_city,seller_state,price,freight_value,order_id,product_id,delivery_delay_days,order_delivery_time
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,106.20,9.56,4a90af3e85dd563884e2afeab1091394,ffb64e34a37740dafb6c88f1abd1fa61,-2.0,8.0
1,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,101.70,15.92,6d953888a914b67350d5bc4d48f2acab,f4621f8ad6f54a2e3c408884068be46d,3.0,28.0
2,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,10.80,2.42,bc8a5de6abf5b14f98a6135a7fb46731,325a06bcce0da45b7f4ecf2797dd40e4,-19.0,2.0
3,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,89.99,45.09,035201c3c82a97f8a25dd6bd5244b2d5,1c36a5285f7f3b1ed2637d7c528ce5ff,-13.0,11.0
4,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,199.90,21.89,0504447548229e075dea8441b37b1e2a,8852eb03b04ec3268a66e9b696e25f6f,-28.0,7.0
...,...,...,...,...,...,...,...,...,...,...
112645,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,16.05,7aa50aad959e4345b45b9732bc346a6e,e891d4a9622cae3b9fc2ec558bda155b,-22.0,5.0
112646,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,10.96,aae373a2cc64ed2d1f262aa56e70b7e8,e891d4a9622cae3b9fc2ec558bda155b,-25.0,3.0
112647,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,16.05,bc34d5b185152cb88b9f5db391dcd1cb,e891d4a9622cae3b9fc2ec558bda155b,-23.0,6.0
112648,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,27.00,12.48,d1edb80f6670902ebbb11765b96873da,e891d4a9622cae3b9fc2ec558bda155b,NaN,NaN
112649,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,12.50,14.52,f7b6b85f6fd2cf9aac15731dca998844,179bb56045bec397c52ef3c8183dabb6,-14.0,8.0

In [24]:
# Which sellers have the highest average delivery delay?

seller_avg_delivery_delay=seller_items_order.groupby("seller_id")[
    ["delivery_delay_days"]
    ].mean()

seller_avg_delivery_delay.sort_values("delivery_delay_days", ascending=False).head(1)

                                  delivery_delay_days
seller_id
df683dfda87bf71ac3fc63063fba369d                167.0

In [25]:
# Which sellers have the longest average delivery time?
seller_delivery_time=seller_items_order.groupby("seller_id")[
    ["order_delivery_time"]
    ].mean()
seller_delivery_time.sort_values("order_delivery_time",ascending=False).head(1)

                                  order_delivery_time
seller_id
df683dfda87bf71ac3fc63063fba369d                189.0

In [27]:
# Are high-revenue sellers also good at delivery performance?
seller_revenue_delivery_performance=(seller_items_order.groupby("seller_id")
                                     .agg(
                                         revenue=("price","sum"),
                                         delivery_performance=("order_delivery_time","mean")
                                     )
                                    )
high_revenue_low_delivery=seller_revenue_delivery_performance[
    (seller_revenue_delivery_performance["revenue"]>seller_revenue_delivery_performance["revenue"].mean())&
    (seller_revenue_delivery_performance["delivery_performance"]<seller_revenue_delivery_performance["delivery_performance"].mean())
    ]

print(high_revenue_low_delivery)

revenue_delivery=seller_items_order[
    ["price","order_delivery_time"]
    ].corr()

print(revenue_delivery)

seller_mean=seller_revenue_delivery_performance["revenue"].mean()
seller_delivery_mean=seller_revenue_delivery_performance["delivery_performance"].mean()
print(seller_mean)
print(seller_delivery_mean)

# Revenue and delivery performance appear to be largely independent in this dataset. While some high-revenue sellers achieve faster-than-average 
# delivery times, the overall relationship between product price and delivery time is negligible (r = 0.062), suggesting that product price is not a 
# meaningful predictor of delivery duration.

                                   revenue  delivery_performance
seller_id
00ee68308b45bc5e2660cd833c3f81cc  20260.00              8.732558
01cf7e3d21494c41fb86034f2e714fa1   9729.36             11.076923
01fdefa7697d26ad920e9e0346d4bd1b  14921.43             10.276923
0241d4d5d36f10f80c644447315af0bd  31397.70             10.467480
02ecc2a19303f05e59ce133fd923fff7   5264.19             10.375000
...                                    ...                   ...
febab0275244b9a49a623f0bd613ca2f   7272.42              7.650794
ff063b022a9a0aab91bad2c9088760b7  12076.50              8.927083
ff1fb4c404b2efe68b03350a8dc24122   6771.00              9.489796
ff4ea69c2a729e83e63c7579e4ef8170   7017.00             10.875000
ff69aa92bb6b1bf9b8b7a51c2ed9cf8b  21940.80             11.000000

[286 rows x 2 columns]
                        price  order_delivery_time
price                1.000000             0.062278
order_delivery_time  0.062278             1.000000
4391.484232633279
11.70578246128739