In [3]:
import pandas as pd

In [4]:
payment_data=pd.read_csv("../Data/Processed/payments_cleaned.csv")
order_data=pd.read_csv("../Data/Processed/orders_cleaned.csv")
customer_data=pd.read_csv("../Data/Processed/customers_cleaned.csv")

In [5]:
# How many total payment records are there?
Total_payment_records=payment_data["order_id"].count()
print(Total_payment_records)

# The total payments records in olist payment data is 103886 duplicates value is also presente in this

103886

In [6]:
# How many unique orders have payment records?
Total_unique_payment_records=payment_data["order_id"].nunique()
print(Total_unique_payment_records)

# There are 99440 payments records that have uique orders

99440

In [7]:
payment_data["payment_installments"].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [8]:
# What are the different payment methods?
payment_method=payment_data["payment_type"].unique()
payment_method

# There are in total 5 different paymenet methods presents

<StringArray>
['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
Length: 5, dtype: str

In [9]:
# What is the total and average payment value?
Total_payment_value=payment_data["payment_value"].sum()
Avg_payment_value=payment_data["payment_value"].mean()

print(Total_payment_value)
print(Avg_payment_value)

# The total payment value is 16008872.120000001 and the avg of this payment value is 154.10038041699556

16008872.120000001
154.10038041699556

In [10]:
# How frequently is each payment method used?
payment_method_freq=payment_data["payment_type"].value_counts()
payment_method_freq

# Mostly credit card payment methood is used frequently and not defined payment method is used only 3 time.

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [11]:
# Which payment methods generate the highest total payment value?

payment_method_value=payment_data.groupby("payment_type")[
    ["payment_value"]
    ].sum()

payment_method_value.sort_values("payment_value",ascending=False)

# Highest  total payment value is done through credit card payment method.

              payment_value
payment_type
credit_card     12542084.19
boleto           2869361.27
voucher           379436.87
debit_card        217989.79
not_defined            0.00

In [12]:
# Which payment methods have the highest average payment value?

Avg_payment_method_value=payment_data.groupby("payment_type")[
    ["payment_value"]
    ].mean()

Avg_payment_method_value.sort_values("payment_value",ascending=False)

# The payment method that generate the highest avg payment value is credit card.

              payment_value
payment_type
credit_card      163.319021
boleto           145.034435
debit_card       142.570170
voucher           65.703354
not_defined        0.000000

In [13]:
# What percentage of payments are made in installments?

Total_payment_installment=payment_data["payment_installments"].sum()
Count_payment_installment=payment_data[
    (payment_data["payment_installments"]>1)
    ].shape[0]

percent_payment_instalation=Total_payment_installment/Count_payment_installment
percent_payment_instalation
# Count_payment_installment
# 285.33488631769444 percentage of payments are made in installments.

np.float64(5.773949121508434)

In [14]:
# Which payment methods are most commonly used for installments?
payment_method_installments=payment_data[
    payment_data["payment_installments"]>1
    ].groupby("payment_type")[
    ["payment_installments"]
    ].count()

payment_method_installments#.sort_values(
#     "payment_installments",
#     ascending=False
# )

# The payments method that are used most commonly for the installments is credit card.

              payment_installments
payment_type
credit_card                  51338

In [15]:
# Does a higher number of installments correspond to higher order values?

installment_order_relation=payment_data[
    ["payment_installments","payment_value"]
    ].corr()

print(installment_order_relation)

# Number of installment and order values have a weak to moderate positive linear realtion as the correlation of Number of installment with order values
# is 0.330811

                      payment_installments  payment_value
payment_installments              1.000000       0.330811
payment_value                     0.330811       1.000000

Merge different table

In [16]:
payments_orders_table=payment_data.merge(
    order_data[["order_id","customer_id"]],
    on="order_id",
    how="left"
)

payments_orders_customer_table=payments_orders_table.merge(
    customer_data[["customer_id","customer_state","customer_city"]],
    on="customer_id",
    how="left"
)

payments_orders_customer_table

,order_id,payment_sequential,payment_type,payment_installments,payment_value,customer_id,customer_state,customer_city
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,0a8556ac6be836b46b3e89920d59291c,MG,teofilo otoni
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,f2c7fc58a9de810828715166c672f10a,SP,sao paulo
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,25b14b69de0b6e184ae6fe2755e478f9,SP,sao paulo
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,7a5d8efaaa1081f800628c30d2b0728f,MG,juiz de fora
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,15fd6fb8f8312dbb4674e4518d6fa3b3,SP,conchas
...,...,...,...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31,5d576cb2dfa3bc05612c392a1ee9c654,SP,atibaia
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80,2079230c765a88530822a34a4cec2aa0,MG,belo horizonte
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77,e4abb5057ec8cfda9759c0dc415a8188,SP,sao paulo
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54,5d719b0d300663188169c6560e243f27,RJ,rio de janeiro
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58,4c7f868f43b5cff577b0becb8c8b7860,RJ,rio de janeiro

In [17]:
# Which customer states generate the highest payment value?
customer_state_payment_value=payments_orders_customer_table.groupby("customer_state")[
    ["payment_value"]
    ].sum()
customer_state_payment_value.sort_values("payment_value",ascending=False).head(1)

# The highest payment value is generated through the sao paulo state.

                payment_value
customer_state
SP                 5998226.96

In [18]:
# What percentage of orders have multiple payment transactions?

multiple_payment_installment=payment_data[
    (payment_data["payment_installments"]>1)
    ].shape[0]

Total_records=payment_data["order_id"].count()

percent_orders_multiple_payment_transaction=multiple_payment_installment/Total_records*100
percent_orders_multiple_payment_transaction

# Total_records
# multiple_payment_installment

# out of 100 the percentage of orders have multiple payment transactions is 49.41763086460158

np.float64(49.41763086460158)

In [19]:
# What is the average number of payment transactions per order?

Total_transaction=payment_data["order_id"].count()  # Do not use payment_installments for this question. An order with payment_installments = 6 still represents one payment record, not six payment transactions.
Total_orders=payment_data["order_id"].nunique()

avg_payment_transaction_per_orders=Total_transaction/Total_orders

avg_payment_transaction_per_orders.astype(int)

# On every order the avg number of payment transaction done is 1

np.int64(1)

In [20]:
# Which orders have the highest total payment value?

order_payment_value=payment_data.groupby("order_id")[
    ["payment_value"]
    ].sum()

order_payment_value.sort_values("payment_value",ascending=False).head(1)

                                  payment_value
order_id
03caa2c082116e1d31e67e9ae3700499       13664.08