In [2]:
import pandas as pd
import numpy as np

In [19]:
review_data=pd.read_csv("../Data/Processed/reviews_cleaned.csv")
order_data=pd.read_csv("../Data/Processed/orders_cleaned.csv")
customer_data=pd.read_csv("../Data/Processed/customers_cleaned.csv")
order_items_data=pd.read_csv("../Data/Processed/order_items_cleaned.csv")
product_data=pd.read_csv("../Data/Processed/products_cleaned.csv")

In [4]:
# How many total reviews are there?

Total_reviews=review_data["review_id"].count()
Total_reviews

# There are 99,224 review records in the dataset.

np.int64(99224)

In [5]:
missing_values=review_data[
    (review_data["review_comment_title"].isna())|
    (review_data["review_comment_message"].isna())
    ]
missing_values

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_type
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,Positive
...,...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30,Positive
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42,Positive
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Positive
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13,Positive
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Negative

In [6]:
# What is the average review score?
avg_review_score=review_data["review_score"].mean()
avg_review_score

# The avg review score is 4.08642062404257

np.float64(4.08642062404257)

In [7]:
# What is the distribution of review scores?

review_distribution=review_data["review_score"].value_counts().sort_index()
review_distribution

# The review score is distributed on the range of 1 to 5 as 5 star review has the highest score that is  57328 and 3 start review has lowest score that
# is 3151

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [8]:
conditions=[review_data["review_score"]<=3,review_data["review_score"]>3]
choices=["Negative","Positive"]
review_data["review_type"]=np.select(conditions,choices,default="Unknown")
review_data

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_type
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,Positive
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,Positive
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,Positive
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Positive
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,Positive
...,...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30,Positive
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42,Positive
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Positive
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13,Positive
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Negative

In [9]:
# What percentage of reviews are positive vs negative?

Total_reviews=review_data["review_score"].count()

Positive_review=review_data[
    (review_data["review_type"]=="Positive")
    ].shape[0]

Negative_review=review_data[
    (review_data["review_type"]=="Negative")
    ].shape[0]

Positive_review_percent=Positive_review/Total_reviews*100
Negative_review_percent=Negative_review/Total_reviews*100

print(Positive_review)
print(Negative_review)
print(Total_reviews)
print(Positive_review_percent)
print(Negative_review_percent)

# Based on the definition used in this analysis, reviews with scores of 4 or 5 are classified as positive, while scores of 1 to 3 are classified as 
# negative. Positive reviews represent a larger proportion of customer feedback, indicating generally positive customer satisfaction.

76470
22754
99224
77.06804805289042
22.931951947109567

In [10]:
# What percentage of reviews contain written comments?
Total_reviews_comments=review_data["review_comment_message"].count()

review_contain_comment=review_data.shape[0]
review_contain_comment_percent=Total_reviews_comments/review_contain_comment*100
print(review_contain_comment_percent)
print(Total_reviews)

# There are 41.29746835443038% of reviews in which customers write the written comments.This means less than half of customers provide detailed 
# textual feedback, so review scores are more widely available than written comments for analyzing customer satisfaction.

41.29746835443038
99224

In [11]:
order_data

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_year,order_purchase_month,order_purchase_month_name,order_delivery_time,delivery_delay_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,2017,10,October,8.0,-8.0,Early
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,2018,7,July,13.0,-6.0,Early
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,2018,8,August,9.0,-18.0,Early
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,2017,11,November,13.0,-13.0,Early
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2018,2,February,2.0,-10.0,Early
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:00,2017-03-09 09:54:00,2017-03-10 11:18:00,2017-03-17 15:08:00,2017-03-28,2017,3,March,8.0,-11.0,Early
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,2018,2,February,22.0,-2.0,Early
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,2017,8,August,24.0,-6.0,Early
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,2018,1,January,17.0,-21.0,Early
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,2018,3,March,7.0,-18.0,Early

Merge different tables

In [24]:
review_orders=review_data.merge(
    order_data[["order_id","customer_id","order_estimated_delivery_date","order_delivered_customer_date","delivery_delay_days","delivery_status"]],
    on="order_id",
    how="left"
)

review_customers=review_orders.merge(
    customer_data[["customer_id","customer_state","customer_city"]],
    on="customer_id",
    how="left"
)

review_order_items_data=review_customers.merge(
order_items_data[["order_id","product_id","seller_id","price","freight_value"]],
                      on="order_id",
                      how="left"
                      )

    
review_products_data=review_order_items_data.merge(
    product_data[["product_id","product_category_name"]],
    on="product_id",
    how="left"
)

review_products_data

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_type,customer_id,order_estimated_delivery_date,order_delivered_customer_date,delivery_delay_days,delivery_status,customer_state,customer_city,product_id,seller_id,price,freight_value,product_category_name
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,Positive,41dcb106f807e993532d446263290104,2018-02-02,2018-01-17 18:42:00,-16.0,Early,SP,osasco,fd25ab760bfbba13c198fa3b4f1a0cd3,6d803cb79cc31c41c4c789a75933b3c7,185.00,13.63,esporte_lazer
1,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,Positive,41dcb106f807e993532d446263290104,2018-02-02,2018-01-17 18:42:00,-16.0,Early,SP,osasco,fd25ab760bfbba13c198fa3b4f1a0cd3,6d803cb79cc31c41c4c789a75933b3c7,185.00,13.63,esporte_lazer
2,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,Positive,8a2e7ef9053dea531e4dc76bd6d853e6,2018-03-14,2018-03-09 23:17:00,-5.0,Early,SP,nova odessa,be0dbdc3d67d55727a65d4cd696ca73c,8e6d7754bc7e0f22c96d255ebda59eba,79.79,8.30,informatica_acessorios
3,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,Positive,e226dfed6544df5b7b87a48208690feb,2018-03-09,2018-02-16 17:28:00,-21.0,Early,BA,santo antonio de jesus,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,149.00,45.12,informatica_acessorios
4,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Positive,de6dff97e5f1ba84a3cd9a3bc97df5f6,2017-05-10,2017-04-20 09:08:00,-20.0,Early,SC,gravatal,52c80cedd4e90108bf4fa6a206ef6b03,a1043bafd471dff536d0c462352beb48,179.99,42.85,ferramentas_jardim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113126,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30,Positive,d8c466a3e7c4cda36cd4ae7d577f44f4,2018-07-20,2018-07-06 13:22:00,-14.0,Early,GO,goiania,4fb209073dc2ab6a6d3c259a7c285501,5343d0649eca2a983820bfe93fc4d17e,226.77,61.20,moveis_decoracao
113127,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42,Positive,d0d7086dea6fcf42b9b690b9f3745c58,2017-12-20,2017-12-08 17:19:00,-12.0,Early,RJ,rio de janeiro,3a33c980b62eb1ef3b8ae61b6fc6fe55,46dc3b2cc0980fb8ec44634e21d2718e,199.99,9.77,brinquedos
113128,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Positive,fcc7b1caafe3b77fd587bab964c4d1fb,2018-04-06,2018-03-21 17:44:00,-16.0,Early,MG,lavras,8ba0118a487ec8671aed57e5ef846574,17ca9b9e9b9ef8fdb529001b49ebb50f,215.97,15.59,papelaria
113129,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13,Positive,3aa00401736823c73e9fe8683328fa6b,2018-07-16,2018-06-30 12:57:00,-16.0,Early,MG,betim,73a7fbf8c1048131f3b531af31bcdf0e,8d956fec2e4337affcb520f56fd8cbfd,50.95,15.46,esporte_lazer
113130,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Negative,f6fff47846276bed044b63474bd38884,2017-07-12,2017-07-02 09:44:00,-10.0,Early,SP,guarulhos,8fbd36d3b045f5f38b252b1513478f38,7e3f87d16fb353f408d467e74fbd8014,32.90,7.78,informatica_acessorios

In [25]:
# Does late delivery lead to lower review scores?

delivery_review=review_orders[
    ["delivery_delay_days","review_score"]
    ].corr()
delivery_review

# The correlation between delivery delay and review score is approximately -0.267, indicating a weak negative relationship. As delivery delays 
# increase, review scores tend to decrease. However, the relationship is not strong, which suggests that other factors besides delivery performance 
# also influence customer satisfaction.

                     delivery_delay_days  review_score
delivery_delay_days             1.000000     -0.266764
review_score                   -0.266764      1.000000

In [28]:
# What is the average review score for early, on-time, and late deliveries?

avg_early_score=review_orders[
    review_orders["delivery_status"]=="early"
    ]["review_score"].mean()

avg_late_score=review_orders[
    review_orders["delivery_status"]=="late"
    ]["review_score"].mean()

avg_on_time_score=review_orders[
    review_orders["delivery_status"]=="on-time"
    ]["review_score"].mean()

print(avg_early_score)
print(avg_late_score)
print(avg_on_time_score)

# Compare the average review scores across early, on-time, and late deliveries. If late deliveries have the lowest average review score, this provides
# further evidence that delivery performance negatively affects customer satisfaction. Early and on-time deliveries are expected to have relatively 
# higher satisfaction scores.

nan
nan
nan

In [29]:
# Which customer states have the lowest average review scores?

state_review_score=review_customers.groupby("customer_state")[
    ["review_score"]
    ].mean()

state_review_score.sort_values("review_score")

# RR state generate the lowest avg review score that is 3.608696 while AP generate the highest 4.194030. States with lower review scores may require 
# further investigation into factors such as delivery performance, seller quality, product quality, or customer experience.

                review_score
customer_state
RR                  3.608696
AL                  3.751208
MA                  3.764075
SE                  3.808023
PA                  3.849174
CE                  3.851016
BA                  3.860888
RJ                  3.874971
PI                  3.920570
PE                  4.011543
PB                  4.018832
ES                  4.041667
GO                  4.042490
AC                  4.049383
RO                  4.051587
DF                  4.064711
SC                  4.071764
TO                  4.096774
MT                  4.102990
RN                  4.105809
MS                  4.118785
RS                  4.133321
MG                  4.136172
SP                  4.173951
PR                  4.180032
AM                  4.183673
AP                  4.194030

In [30]:
# Which customer states have the highest percentage of negative reviews?

state_negative_review = review_customers[
    review_customers["review_type"] == "Negative"
].groupby("customer_state").size()

Total_state_review=review_customers.groupby(
    "customer_state"
).size()

state_negative_review_percent=state_negative_review/Total_state_review*100

state_negative_review_percent

# RR state have 39.130435% of negative review which is highest among all the state while AM have the lowest negative review. This suggests that 
# customer satisfaction may be weaker in this state. However, the total number of reviews should also be considered because a state with a small 
# number of reviews can show a high negative-review percentage.

customer_state
AC    25.925926
AL    30.917874
AM    19.047619
AP    19.402985
BA    28.924635
CE    29.721595
DF    22.951583
ES    23.908730
GO    24.258893
MA    31.635389
MG    21.634409
MS    21.823204
MT    22.369878
PA    29.545455
PB    25.612053
PE    24.605103
PI    26.883910
PR    20.047638
RJ    28.962005
RN    22.199170
RO    26.190476
RR    39.130435
RS    21.539303
SC    23.544024
SE    30.085960
SP    20.542096
TO    21.863799
dtype: float64

In [31]:
# Which product categories have the highest average review scores?

product_category_review_score=(review_products_data.groupby("product_category_name")
    .agg(
        Score=("review_score","mean"),
        Total_number_score=("review_score","count")
    )
                              )
                        
product_category_review_score.sort_values("Score",ascending=False)

# The product category cds_dvds_musicais have the highest avg review score 4.642857. This suggests strong customer satisfaction for this category. 
# However, the number of reviews should also be considered because a high average score based on a small number of reviews may not represent overall
# category performance.

                                                  Score  Total_number_score
product_category_name
cds_dvds_musicais                              4.642857                  14
fashion_roupa_infanto_juvenil                  4.500000                   8
livros_interesse_geral                         4.446266                 549
construcao_ferramentas_ferramentas             4.444444                  99
flores                                         4.419355                  31
...                                                 ...                 ...
moveis_escritorio                              3.493183                1687
pc_gamer                                       3.333333                   9
portateis_cozinha_e_preparadores_de_alimentos  3.266667                  15
fraldas_higiene                                3.256410                  39
seguros_e_servicos                             2.500000                   2

[74 rows x 2 columns]

In [32]:
# Which sellers have the highest average review scores?

seller_review_score=review_products_data.groupby("seller_id")[
    ["review_score"]
    ].mean()

seller_review_score.sort_values("review_score",ascending=False)

# There are multiple sellers that have the highest avg review scores of 5. However, average review score alone may be misleading because some sellers
# may have received very few reviews. Therefore, seller review volume should be considered before concluding which sellers consistently deliver the 
# best customer experience.

                                  review_score
seller_id
feb793c88d836c3a75efa4b5a3465d70           5.0
e59e575a175fadcadf8479e191770425           5.0
e595809a6c31ec4314fd06ef198c244d           5.0
e560e4022d8f7aebf155db95946c5c0f           5.0
e5545d4d4473876ea78c5bcebca365c3           5.0
...                                        ...
3a79f35a2344ede41af21267f61d5ec6           1.0
fc6295add6f51a0936407ead70c1001d           1.0
fc99f99385ae90f66f01733856fb88c9           1.0
ad738d3fcf42655ed15c4960b7b6c601           1.0
ad8ada0ffa993cb1197d102d9ab21a3e           1.0

[3090 rows x 1 columns]

In [33]:
# Which sellers have both high revenue and low review scores?

seller_revenue_review_score=(review_order_items_data.groupby("seller_id")
                             .agg(
                                 Revenue=("price","sum"),
                                 Review_score=("review_score","mean")
                             )
                            )
seller_high_revenue_low_review_score=seller_revenue_review_score[
    (seller_revenue_review_score["Revenue"]>seller_revenue_review_score["Revenue"].mean())&
    (seller_revenue_review_score["Review_score"]<seller_revenue_review_score["Review_score"].mean())
    ]

seller_high_revenue_low_review_score
    
# These sellers generate above-average revenue but receive below-average review scores. They are an important business segment because strong sales do
# not necessarily indicate strong customer satisfaction. The business should investigate whether delivery issues, product quality, seller service, or 
# other factors are contributing to their lower ratings.

                                   Revenue  Review_score
seller_id
001cca7ae9ae17fb1caed9dfb1094831  24770.03      3.902542
00fc707aaaad2d31347cf883cd2dfe10  13315.90      3.737589
014c0679dd340a0e338872e7ec85666a   7058.00      3.666667
02d35243ea2e497335cd0f076b45675d   5794.00      2.687500
0307f7565ff85b299b6e5ef162b1b1a9   4728.80      3.142857
...                                    ...           ...
f84a00e60c73a49e7e851c9bdca3a5bb   5949.94      3.666667
fcb5ace8bcc92f75707dc0f01a27d269   8200.73      3.808219
fcdd820084f17e9982427971e4e9d47f   4783.99      3.259259
ff69aa92bb6b1bf9b8b7a51c2ed9cf8b  21940.80      3.650000
fffd5413c0700ac820c7069d66d98c89   8870.90      3.866667

[218 rows x 2 columns]

In [34]:
# Do higher-priced products receive higher or lower review scores?

# review_type_customers.drop("review_type_y",inplace=True,axis=1)
order_value_review_score=review_products_data[
    ["price","review_score"]
    ].corr()

order_value_review_score


# The correlation between product price and review score is -0.003941, indicating virtually no linear relationship between the two variables. Higher-
# priced products do not appear to receive systematically higher or lower review scores.Product price does not appear to have a meaningful association
# with review scores.

                 price  review_score
price         1.000000     -0.003941
review_score -0.003941      1.000000

In [35]:
# Do higher-value orders receive higher or lower review scores?

order_value=order_items_data.groupby("order_id").agg(
    Order_value=("price","sum")
)

order_value_review=review_data.merge(
    order_value,
    on="order_id",
    how="left"
)

order_value_review_score=order_value_review[
    ["Order_value","review_score"]
].corr()

order_value_review_score

# The correlation between order value and review score is very close to zero, indicating virtually no linear relationship. Higher-value orders do not
# systematically receive higher or lower review scores. Therefore, order value alone does not appear to have a meaningful association with customer 
# satisfaction.

              Order_value  review_score
Order_value      1.000000     -0.039672
review_score    -0.039672      1.000000

In [37]:
# Which states have both high delivery delays and low review scores?

state_delivery_delay_review_score=(
     review_customers.groupby("customer_state")
     .agg(
         Delivery_delay=("delivery_delay_days","mean"),
         Review_score=("review_score","mean")
     )
 )
# review_orders
high_delivery_delay_low_score=(
     state_delivery_delay_review_score[
         (
             state_delivery_delay_review_score["Delivery_delay"]
             >
             state_delivery_delay_review_score["Delivery_delay"].mean()
         )
         &
         (
             state_delivery_delay_review_score["Review_score"]
             <
             state_delivery_delay_review_score["Review_score"].mean()
         )
     ]
 )

high_delivery_delay_low_score

                Delivery_delay  Review_score
customer_state
AL                   -8.821608      3.751208
BA                  -10.886630      3.860888
CE                  -10.868339      3.851016
MA                   -9.719274      3.764075
PI                  -11.286017      3.920570
RJ                  -11.816998      3.874971
SE                  -10.068862      3.808023