In [1]:
import pandas as pd
import numpy as np

In [2]:
order_items_data=pd.read_csv("../Data/Processed/order_items_cleaned.csv")
product_data=pd.read_csv("../Data/Processed/products_cleaned.csv")
customer_data=pd.read_csv("../Data/Processed/customers_cleaned.csv")
order_data=pd.read_csv("../Data/Processed/orders_cleaned.csv")

In [3]:
# How many total order-item records are there?
Total_order_items=order_items_data["order_id"].count()
print(Total_order_items)

# There is 112650 order items records which is order by the customers among these there are repeated products also

112650

In [4]:
# What is the average product price and freight value?

Avg_product_price = order_items_data["price"].mean()
Avg_freight_value=order_items_data["freight_value"].mean()
print(Avg_product_price)
print(Avg_freight_value)

# The avg product price per order items is 120.653 and freight/shipping charge is 19.990 these avg includes the repeated items also

120.65373901464713
19.990319928983578

In [5]:
# "What is the average total price per unique product?"
Total_price_per_product = (
    order_items_data
    .groupby("product_id")["price"]
    .sum()
)

Avg_product_price = Total_price_per_product.mean()

Avg_product_price

# avg of unique product price is 412.480
# "avg of unique product price" That could be misunderstood as the average unit price of unique products.

# It actually means: On average, each unique product generated 412.48 in cumulative product sales across all its order-item transactions.

np.float64(412.4804618979697)

In [6]:
# What is the average number of items per order?
item_per_order=(order_items_data.groupby("order_id")
["order_item_id"].count()
               )
Avg_item_per_order=item_per_order.mean()
Avg_item_per_order

# on avg the number of items per order is 1.1417

np.float64(1.1417306873695092)

In [7]:
# What percentage of orders contain multiple items?

Total_orders=order_items_data["order_id"].nunique()

item_per_order=(order_items_data.groupby("order_id")
["product_id"].count()
               )

item_multiple_order=item_per_order[item_per_order>1].count()
item_multiple_order_percent=item_multiple_order/Total_orders*100

print(item_multiple_order_percent)

# 9.93% of order contain the multiple items

9.93554010500071

In [8]:
# What is the total product revenue? sales kpi
Total_product_revenue=order_items_data["price"].sum()
Total_product_revenue

# Total product sales generate 13591643.7 revenue

np.float64(13591643.7)

In [9]:
# What is the total revenue including freight?
Total_revenue=order_items_data["price"].sum()
Total_freight_value=order_items_data["freight_value"].sum()
Total_sales=Total_revenue+Total_freight_value
print(Total_sales)

# Total order value including freight = 15.84M

15843553.239999998

In [10]:
order_items_product=order_items_data.merge(
    product_data[["product_id","product_category_name"]],
    on="product_id",
    how="left"
)

order_items_order=order_items_product.merge(
    order_data[["order_id","customer_id","order_status"]],
    on="order_id",
    how="left"
)

order_items_customer=order_items_order.merge(
    customer_data[["customer_id","customer_unique_id","customer_state","customer_city"]],
    on="customer_id",
    how="left"
)

order_items_customer

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,customer_id,order_status,customer_unique_id,customer_state,customer_city
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:00,58.90,13.29,cool_stuff,3ce436f183e68e07877b285a838db11a,delivered,871766c5855e863f6eccc05f988b23cb,RJ,campos dos goytacazes
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:00,239.90,19.93,pet_shop,f6dd3ec061db4e3987629fe6b26e5cce,delivered,eb28e67c4c0b83846050ddfb8a35d051,SP,santa fe do sul
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:00,199.00,17.87,moveis_decoracao,6489ae5e4333f3693df5ad4372dab6d3,delivered,3818d81c6709e39d06b2738a8d3a2474,MG,para de minas
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:00,12.99,12.79,perfumaria,d4eb9395c8c0431ee92fce09860c5a06,delivered,af861d436cfc08b2c2ddefd0ba074622,SP,atibaia
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:00,199.90,18.14,ferramentas_jardim,58dbd0b2d70206bf40e62cd34e84d795,delivered,64b576fb70d441e8f1b2d7d446e483c5,SP,varzea paulista
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:00,299.99,43.41,utilidades_domesticas,b51593916b4b8e0d6f66f2ae24f2673d,delivered,0c9aeda10a71f369396d0c04dce13a64,MA,sao luis
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:00,350.00,36.53,informatica_acessorios,84c5d4fbaf120aae381fad077416eaa0,delivered,0da9fe112eae0c74d3ba1fe16de0988b,PR,curitiba
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:00,99.90,16.95,esporte_lazer,29309aa813182aaddc9b259e31b870e6,delivered,cd79b407828f02fdbba457111c38e4c4,SP,sao paulo
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:00,55.99,8.72,informatica_acessorios,b5e6afd5a41800fdf401e0272ca74655,delivered,eb803377c9315b564bdedad672039306,SP,vinhedo
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:00,43.00,12.79,cama_mesa_banho,96d649da0cc4ff33bb408b199d4c7dcf,delivered,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,SP,botucatu

In [11]:
# Which product categories generate the highest revenue?
highest_revenue_category=(order_items_product.groupby("product_category_name")
["price"].sum()
)
highest_revenue_category.sort_values(ascending=False)

# beleza_saude generate highest categories revenue as it is possible that it avg product price is highest among all the other category while 
# seguros_e_servicos generate the lowest revenue as it avg product price is lowest among all while the futher analaysis can be donento prove this 
# point and other factors is also responsible for the category revenue

# Beleza_saude generates the highest product revenue among the categories, with approximately 1.26M in sales. Further analysis of sales volume and 
# average selling price is required to determine the main drivers of its high revenue.

product_category_name
beleza_saude                     1258681.34
relogios_presentes               1205005.68
cama_mesa_banho                  1036988.68
esporte_lazer                     988048.97
informatica_acessorios            911954.32
                                    ...
flores                              1110.04
casa_conforto_2                      760.27
cds_dvds_musicais                    730.00
fashion_roupa_infanto_juvenil        569.85
seguros_e_servicos                   283.29
Name: price, Length: 74, dtype: float64

In [12]:
# Which product categories have the highest number of items sold?
highest_item_sold_category=order_items_product.groupby("product_category_name")[
    ["product_id"]
    ].count()
highest_item_sold_category.sort_values("product_id",ascending=False)

# Cama_mesa_banho has the highest sales volume, with 11,115 product items sold.

                               product_id
product_category_name
cama_mesa_banho                     11115
beleza_saude                         9670
esporte_lazer                        8641
moveis_decoracao                     8334
informatica_acessorios               7827
...                                   ...
cds_dvds_musicais                      14
la_cuisine                             14
pc_gamer                                9
fashion_roupa_infanto_juvenil           8
seguros_e_servicos                      2

[74 rows x 1 columns]

In [13]:
# Which sellers generate the highest revenue?
seller_highest_revenue=order_items_data.groupby("seller_id")[
    ["price"]
    ].sum()
seller_highest_revenue.sort_values("price",ascending=False).head(1)

                                      price
seller_id
4869f7a5dfa277a7dca6462dcf3b52b2  229472.63

In [14]:
# Which products generate the highest revenue?
product_highest_revenue=order_items_data.groupby("product_id")[
    ["price"]
    ].sum()
product_highest_revenue.sort_values("price",ascending=False).head(1)

                                    price
product_id
bb50f2e236e5eea0100680137654686c  63885.0

In [15]:
# Which categories have high sales volume but relatively low revenue?

category_distribution = (
    order_items_product
    .groupby("product_category_name")
    .agg(
        sales_volume=("product_id", "count"),
        revenue=("price", "sum")
    )
)

category_distribution.sort_values(
    ["sales_volume", "revenue"],
    ascending=[False, True]
)                  

# while seguros_e_servicos has lowest sales but lowest revenue as sales factor is not only helful in generatinng the highest revenue for the particular 
# category while beleza_saude has highest sales but  not having highest revenue  This indicates that sales volume alone does not determine revenue; 
# the selling price of products also plays an important role.

                               sales_volume     revenue
product_category_name
cama_mesa_banho                       11115  1036988.68
beleza_saude                           9670  1258681.34
esporte_lazer                          8641   988048.97
moveis_decoracao                       8334   729762.49
informatica_acessorios                 7827   911954.32
...                                     ...         ...
cds_dvds_musicais                        14      730.00
la_cuisine                               14     2054.99
pc_gamer                                  9     1545.95
fashion_roupa_infanto_juvenil             8      569.85
seguros_e_servicos                        2      283.29

[74 rows x 2 columns]

In [16]:
# Which sellers have high sales volume but low average order value?

seller_distribution=(order_items_data.groupby("seller_id")
                     .agg(
                         sales_volume=("product_id","count"),
                         total_orders=("order_id","nunique"),
                         total_revenue=("price","sum")
                     )
                    )

seller_distribution["Avg_order_value"]=(seller_distribution["total_revenue"]/seller_distribution["total_orders"])

high_volume_low_aov = seller_distribution[
    (seller_distribution["sales_volume"] > seller_distribution["sales_volume"].mean()) &
    (seller_distribution["Avg_order_value"] < seller_distribution["Avg_order_value"].mean())
]
high_volume_low_aov.sort_values(
    "sales_volume",
    ascending=False
).head(1)

# These sellers have high sales volume but relatively low average order value. This suggests that they sell a large number of items, but the average 
# monetary value generated per order is comparatively low.

,sales_volume,total_orders,total_revenue,Avg_order_value
seller_id,,,,
6560211a19b47992c3666cc44a7e94c0,2033,1854,123304.83,66.50746

In [17]:
# Which customer states generate the highest order-item revenue?
customer_state_revenue=order_items_customer.groupby("customer_state")[
    ["price"]
    ].sum()

customer_state_revenue.sort_values("price",ascending=False)

# sao paulo generate the highest revenue

                     price
customer_state
SP              5202955.05
RJ              1824092.67
MG              1585308.03
RS               750304.02
PR               683083.76
SC               520553.34
BA               511349.99
DF               302603.94
GO               294591.95
ES               275037.31
PE               262788.03
CE               227254.71
PA               178947.81
MT               156453.53
MA               119648.22
MS               116812.64
PB               115268.08
PI                86914.08
RN                83034.98
AL                80314.81
SE                58920.85
TO                49621.74
RO                46140.64
AM                22356.84
AC                15982.95
AP                13474.30
RR                 7829.43

In [18]:
customer_state_revenue_analysis=(order_items_customer.groupby(["customer_state","product_category_name"])
    .agg(
        revenue=("price","sum"),
        total_product=("product_id","count")
    )
                       )
customer_state_revenue_analysis.sort_values(
    ["revenue","total_product"],
    ascending=[False,False]
)

# Sao paulo genertate highest state revenue because of its cama_mesa_banho product category as its revenue is highest among all other state and this 
# state sold highest products quantity

# São Paulo generates the highest overall order-item revenue. Within São Paulo, cama_mesa_banho is the highest-revenue product category, generating 
# 478,284.52. This category is therefore an important contributor to revenue in São Paulo, although the state's overall revenue is generated across 
# multiple categories.

                                                     revenue  total_product
customer_state product_category_name
SP             cama_mesa_banho                     478284.52           5235
               beleza_saude                        462305.22           4204
               relogios_presentes                  435009.92           2281
               esporte_lazer                       386357.01           3667
               informatica_acessorios              350747.88           3170
...                                                      ...            ...
AL             bebidas                                 15.49              1
BA             casa_conforto_2                         12.90              1
ES             casa_conforto_2                         12.90              1
PR             casa_conforto_2                         12.90              1
MS             construcao_ferramentas_ferramentas       6.80              1

[1394 rows x 2 columns]

In [19]:
# Which categories have the highest average freight value?
category_avg_freight_value=order_items_product.groupby("product_category_name")[
    ["freight_value"]
    ].mean()
category_avg_freight_value.sort_values("freight_value",ascending=False)

# pcs has the highest avg freight value

                                                freight_value
product_category_name
pcs                                                 48.454680
eletrodomesticos_2                                  44.538571
moveis_colchao_e_estofado                           42.906842
moveis_cozinha_area_de_servico_jantar_e_jardim      42.702598
moveis_quarto                                       42.497523
...                                                       ...
alimentos                                           14.256922
casa_conforto_2                                     13.677000
fashion_roupa_feminina                              12.953125
livros_importados                                   12.830833
fashion_roupa_infanto_juvenil                       11.938750

[74 rows x 1 columns]

In [20]:
# Which category contributes most to each customer state's revenue?

state_category_revenue = (
    order_items_customer
    .groupby(["customer_state", "product_category_name"])["price"]
    .sum()
    .reset_index()
)

top_category_by_state = (
    state_category_revenue
    .loc[
        state_category_revenue
        .groupby("customer_state")["price"]
        .idxmax()   # idxmax() means: Find the index/row position where the maximum value occurs.
    ]
    .sort_values("price", ascending=False)
)

top_category_by_state


# Remember, idxmax() gave us the row indexes where each state's revenue is highest..loc[] says:Go back to state_category_revenue and select those specific rows.

     customer_state   product_category_name      price
1295             SP         cama_mesa_banho  478284.52
995              RJ      relogios_presentes  185379.65
490              MG            beleza_saude  157558.30
1119             RS         cama_mesa_banho   60270.74
924              PR      relogios_presentes   59967.04
139              BA            beleza_saude   51367.91
1205             SC           esporte_lazer   44116.90
767              PE            beleza_saude   41604.78
424              GO      relogios_presentes   33257.72
301              DF      relogios_presentes   32730.37
202              CE            beleza_saude   32419.18
360              ES      relogios_presentes   29461.00
668              PA            beleza_saude   23755.83
718              PB            beleza_saude   16286.98
613              MT            beleza_saude   15301.79
1009             RN            beleza_saude   13886.47
35               AL            beleza_saude   12780.26
437              MA            beleza_saude   12747.18
559              MS            beleza_saude   11289.57
826              PI            beleza_saude   10290.19
1244             SE            beleza_saude    8883.66
1054             RO            beleza_saude    7085.76
1389             TO      relogios_presentes    5446.89
77               AM            beleza_saude    2776.03
120              AP  informatica_acessorios    2149.52
10               AC           esporte_lazer    1677.46
1097             RR           esporte_lazer    1350.60